# Generated by Django 5.0.4 on 2024-06-20 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_clase', models.CharField(max_length=255)),
                ('tarifa_clase', models.IntegerField()),
                ('idioma_clase', models.CharField(max_length=255)),
                ('descripcion_clase', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_educativo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estado_solicitud', models.CharField(max_length=50)),
                ('correo_padre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(max_length=10)),
                ('antecedentes', models.FileField(upload_to='archivos_pdf')),
                ('certificado', models.FileField(upload_to='archivos_pdf')),
                ('carnet', models.ImageField(upload_to='media')),
                ('descripcion', models.TextField()),
                ('estado_de_aprobacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media')),
                ('sexo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('edad', models.CharField(max_length=3)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contra', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('tipo_de_usuario', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClaseMateria',
            fields=[
                ('id_clasemateria', models.AutoField(primary_key=True, serialize=False)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clase')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materia')),
            ],
            options={
                'unique_together': {('clase', 'materia')},
            },
        ),
        migrations.AddField(
            model_name='clase',
            name='materias',
            field=models.ManyToManyField(through='core.ClaseMateria', to='core.materia'),
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('recomendacion', models.CharField(blank=True, max_length=700, null=True)),
                ('valoracion', models.IntegerField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clase')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudiante')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_profesor', to='core.profesor'),
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaclase', models.DateTimeField()),
                ('contacto', models.CharField(blank=True, max_length=15)),
                ('mensaje', models.TextField(default='')),
                ('estado_clase', models.CharField(default='Pendiente', max_length=50)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_clase', to='core.clase')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudiante')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_profesor', to='core.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='profesor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
