# Generated by Django 5.0.4 on 2024-06-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='horaclase',
            field=models.TimeField(default=''),
        ),
    ]
