# Generated by Django 5.0.4 on 2024-06-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='estado_realizacion',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
