# Generated by Django 5.0.4 on 2024-05-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_fechadeinicio_sesion_fechaclase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='estado_clase',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
