# Generated by Django 5.0.4 on 2024-06-24 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sesion_horaclase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='horaclase',
        ),
    ]
